/**
 * Do not modify this file ! 
 * This file is read & written by GPT-3
 * 
 * Every Doclet with an @autogenerated tag is from GPT-3
 */

/**
 * @autogenerated
 * @desc A simple function to greet a person by their name.
 * @summary This function takes a name as input and logs a greeting message to the console.
 * @param {string} name - The name of the person to greet.
 * @returns {void}
 */
function Greet(name) {
    console.log(`Hello ${name}`);
}

/**
 * @autogenerated
 * @desc Calculates the sum of all elements in an array.
 * @summary A function that takes an array of numbers and returns the sum of its elements.
 * @param {number[]} arr - The array of numbers to be summed.
 * @returns {number} The sum of all elements in the input array.
 */
function sum(arr) {
    let sum = 0;
    
    for (let i = 0; i < arr.length; i++)
        sum += arr[i];
    
    return sum;
}

