/**
 * Do not modify this file ! 
 * This file is read & written by GPT-3
 * 
 * Every Doclet with an @autogenerated tag is from GPT-3
 */

/**
 * @autogenerated
 * @summary Greet someone with a personalized message
 * 
 * @desc This function logs a personalized message to the console, based on the name provided as an argument.
 * 
 * @param {string} name The name to include in the personalized message.
 */
function Greet(name) {
    console.log(`Hello ${name}`);
}

/** 
 * @autogenerated
 * @summary Calculates the sum of all elements of an array
 * 
 * @param {number[]} arr The array of numbers to sum
 * 
 * @returns {number} The sum of all elements of the array
 */
function sum(arr) {
    let sum = 0;
    
    for (let i = 0; i < arr.length; i++)
        sum += arr[i];
    
    return sum;
}

