/**
 * Do not modify this file ! 
 * This file is read & written by GPT-3
 * 
 * Every Doclet with an @autogenerated tag is from GPT-3
 */

/**
 * @autogenerated
 * @desc Greet function that logs a greeting message with the given name.
 * @summary This function takes a name as an input and logs a greeting message with the given name.
 * @param {string} name - The name to be included in the greeting message.
 * @returns {void}
 */
function Greet(name) {
    console.log(`Hello ${name}`);
}

/**
 * @autogenerated
 * @desc Sums the elements of an array.
 * @summary This function takes an array of numbers and returns the sum of its elements.
 * @param arr {number[]} - The array of numbers to sum.
 * @returns {number} - The sum of the elements in the input array.
 */
function sum(arr) {
    let sum = 0;
    
    for (let i = 0; i < arr.length; i++)
        sum += arr[i];
    
    return sum;
}

